### PR TITLE
165 bug/validation invite emails

### LINKED ISSUE #165: Add validation to adding invite emails
image

### PR DESCRIPTION
**Pull request by alisondraV**
## Description

Add validation to adding invite emails.
image

## Fixes

Closes #165 

## Checklist

- [ ] This change brings new tests
- [ ] This change breaks any integration tests
- [ ] This change includes comments for sophisticated areas

### CODE REVIEW

File: src/components/VInput.vue [hunk 1]
```diff
@@ -1,13 +1,16 @@
 <template>
   <div>
     <label class="flex flex-col text-secondary-text">
-      <span class="text-left mb-1 text-sm">{{ label }}</span>
+      <span class="text-left mb-1 text-sm" :class="isFocused ? 'text-primary-green' : ''">
```
Comment (ANDREYDEN) [inline src/components/VInput.vue]: We can use class binding here
```suggestion
      <span class="text-left mb-1 text-sm" :class="{ 'text-primary-green' : isFocused }">
```

File: src/views/CreateFamily.vue [hunk 2]
```diff
@@ -25,12 +24,14 @@
...
             placeholder="Enter member's email"
             v-model="currentEmail"
+            :error="errorType === 'email'"
           />
           <img
             alt="Add"
             class="mt-6"
             data-cy="add-member"
             src="@/assets/images/PlusIcon.svg"
+            :class="isEmailInValidState ? 'visible' : 'hidden'"
```
Comment (ANDREYDEN) [inline src/views/CreateFamily.vue]: This is fine to leave as is, but we could re-write it with class bindings in case there are going to be more class name properties in the future
```suggestion
            :class="{ visible: isEmailInValidState, hidden: !isEmailInValidState }"
```

File: src/views/CreateFamily.vue [hunk 3]
```diff
@@ -88,13 +90,16 @@ export default class CreateFamily extends Mixins(ValidationMixin) {
...
-    );
+    return this.isDisplayNameValid(this.familyName);
+  }
+
+  get isEmailInValidState() {
+    return this.currentEmail !== '' && this.isEmailValid(this.currentEmail);
   }
 
   addEmail() {
+    if (!this.isEmailInValidState) return;
```
Comment (ANDREYDEN) [inline src/views/CreateFamily.vue]: Is this a safeguard? The add button wouldn't be shown if the email is invalid, so this method would never be called with invalid email.

**Review by ANDREYDEN — CHANGES_REQUESTED** [review]
Looks good, apart from the comments I would also make sure we have consistency in error states (if the email is correct, the error shouldn't be shown:
image

File: src/views/CreateFamily.vue (hunk 2 above)
Comment (alisondraV) [reply src/views/CreateFamily.vue]: I don't think it's necessary at the moment

File: src/components/EmailsList.vue [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+    return this.currentEmail !== '' && this.isEmailValid(this.currentEmail);
+  }
+
+  addEmail() {
+    this.memberEmails.push(this.currentEmail);
+    this.currentEmail = '';
+  }
+
+  removeEmail(email: string) {
+    this.memberEmails.splice(this.memberEmails.indexOf(email), 1);
```
Comment (ANDREYDEN) [inline src/components/EmailsList.vue]: possible alternative:
```suggestion
    this.memberEmails = this.memberEmails.filter(e => e != email);
```

**Review by ANDREYDEN — APPROVED** [review]
Looks good, just one consideration
