### PR TITLE
Bugfix 184/fix warnings and home page url

### LINKED ISSUE #184: Fix the Home page url and Vue warns

### PR DESCRIPTION
**Pull request by alisondraV**
## Description

Fix Vue warnings and make sure Storage shows up on the home route ('/').

## Fixes

Closes #184 

## Checklist

- [ ] This change brings new tests
- [x] This change doesn't break any integration tests
- [ ] This change includes comments for sophisticated areas

### CODE REVIEW

File: src/components/StatisticsDisplay.vue [hunk 1]
```diff
@@ -57,13 +55,15 @@ export default class StatisticsDisplay extends Vue {
...
     const filteredStats = sortedStatistics.filter(item => parseInt(this.getCategoryPercentage(item[0])) > 5);
     const miscellaneousCategory = sortedStatistics
       .filter(item => parseInt(this.getCategoryPercentage(item[0])) <= 5)
       .reduce((item, prev) => ['miscellaneous', prev[1] + item[1]], ['miscellaneous', 0]);
 
-    this.statistics = Object.fromEntries([...filteredStats, miscellaneousCategory]);
+    const filteredStatsWithMiscCategory =
+      miscellaneousCategory[1] !== 0 ? [...filteredStats, miscellaneousCategory] : filteredStats;
+
+    return Object.fromEntries(filteredStatsWithMiscCategory);
```
Comment (ANDREYDEN) [inline src/components/StatisticsDisplay.vue:66]: If we apply the filter for dropping categories with value of <5 at the end, then we can get rid of lines 63 and 64

**Review by ANDREYDEN — CHANGES_REQUESTED** [review]
A small suggestion

File: src/components/StatisticsDisplay.vue (hunk 1 above)
Comment (alisondraV) [reply src/components/StatisticsDisplay.vue:66]: It would result in loosing miscellaneous category, which we always want to display

**Review by ANDREYDEN — APPROVED** [review]
